sudo: required

services:
  - docker

env:
  global:
    - secure: "i4weGRjMRbVzRCW3VTN1dXRldV5/qyXwzB2jM+1QhNAJYNWaMv9W+C+DbJzaOpoEE6AYEmhc1RXn2LYpRKRMHQx4lLQMOhb0ocyfyusDUeOi0hk3uzDApKtGiDKcMm13fHukUpQ7L1IlfkFBRIIwB3mDXn+HU9hyvhI9ei3YN1IwrdkmPZq08LeZTtfOBDxXlcS7n8RPHHN+AcahXy6/VyRSwS1oTSYKBYC8PLasPO3zcq8Gir9Sd1vFkg4g9Gc7pQKRYOyM/p+UXRfzeHmcCMXA2qHd2fk0fWd5dAIL30vIMslh0rRzvNpBoEFJHPW31ZJD7teh/SzdP1qElWpRwONmu1Z0LsFoAgor2H2SBb3yOTLWA2Ohcy39LlwD5Fw9co2ebJ7p9qUPFlYGC7k7vSVzHIZTNFpr7mt4gEg0D2UHyLPCmEkp26QTrgibyZb6+cPIR6oiNQZckPln8obcDhx75PY+U/wpYlj6PiR0d3HdqwmWt5ADd8BiMv+Py9BT9cPo3v14XYpdYyWc4GdMRXb5nI0/X7PQaeSQ4TULU7GcTYWIDF2WoexsiLpfVyT2dMxyqHYTJTcitlqHI6Jf1Y9SivnTpsDww4AI285McotjOv/Jsc2FSz/pASM7p7fxR1gIwLjWnySOTJZXkyd95p62rMAPL4rq0EDhdRZf8lc="
    - secure: "hmzGR+ikAnnz/BpvXE5XVGfaaOTw6dJuRfKSWN1NUEDkMh5LphofiwkZFFcWpYmPYTE0EcSbcgBOOUHu/QKv+4+Q8hKk1TUsvRclxAht/f/dyQ1EqXiqn59y7fX7tQyKl3r4HE4qmoiQUV23sAn0u44MjaVZYBYFjs2MamfkpM5tDZc6a/ybolDpOuK7N/T56NrJ6OA6svKUqIO2JhL0wsjEX7KbZOUN7/4zKUsg7cP6hvwsBbZ26FQzSn3pEAS5yjH0GT3W8AlZ2yYWKwgHowwVUjdZks5S9BQcnLY6URuSDW2w6QA2KSC5LLQe+iyhJg5aLXUYczOBYkwlV6QN6teHTF3bA8NSbOkRx4Aaggzi9KmUPJC9wlHWUdYZngqHvY8huRvTyKm16cgnCPRDPVJFGSP7ahEG0z20ru6tvA2xEtTCdVp9jUkji0Q8OQGvvg3+BxsX4TAeEr4n58mWGFYF1YB57z9Wb0MDZHRKEskZQnOJtPgqWqO6/tI7fHqBF+3cCerYjaSSG8TJVqB/sBWYbDWG5l6DEhV6uObaQmLOg+YeQh4qNtan535z78YXV8Z1HZFW3ITMQu6HLcDY1kgA8JwjhV3ncW466Mfhj3OZZ7pf2dBjX0hqELa6SywsrUMYAU6/nAIaI6eNFgJcapsc9981CUFULnzZfLuYUTg="

script:
  - bash docker-build.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images

